### ISSUE TITLE
bug: 'crash' when query param shuffle_deck_when_empty is not numeric

### ISSUE THREAD

**Issue by ashleybaldock** [salinecitrine/noita-wand-simulator#16]
e.g. shuffle_deck_when_empty=No causes the page to fail to load

**Comment by salinecitrine** [comment]
I think this is just when it's not valid JSON (which then I believe gets coerced into a boolean).

does this come up during normal usage, or only when editing the URL directly?

**Comment by ashleybaldock** [comment]
Only seen it editing the URL 'manually' (the wiki uses Yes and No for the booleans and one made it into the url generated by the wand template).

Easy to trap errors from [the json.parse](https://github.com/salinecitrine/noita-wand-simulator/blob/master/src/app/redux/util.ts#L31) and use whatever the default value is (and maybe a message warning the url was broken if I feel super fancy).

**Comment by ashleybaldock** [comment]
Fixed in #40
