### ISSUE TITLE
Omega->Mu->Wand Refresh bug

### ISSUE THREAD

**Issue by ashleybaldock** [salinecitrine/noita-wand-simulator#24]
Sim link to example: https://noita-wand-simulator.salinecitrine.com/?actions_per_round=1&deck_capacity=26&reload_time=0&shuffle_deck_when_empty=false&cast_delay=0&mana_charge_speed=20000&mana_max=20000&spread=0&spells=OMEGA,RESET,MU,DAMAGE,LIGHT_BULLET

<img width="754" alt="Screenshot 2023-05-18 at 19 30 33" src="https://github.com/salinecitrine/noita-wand-simulator/assets/1220581/6f05e31c-8e8b-4cf2-b23b-3596b74fe521">
<img width="740" alt="Screenshot 2023-05-18 at 19 30 43" src="https://github.com/salinecitrine/noita-wand-simulator/assets/1220581/a5331cb0-003d-47cf-9e5c-a011a67a8238">
<img width="476" alt="Screenshot 2023-05-18 at 19 30 18" src="https://github.com/salinecitrine/noita-wand-simulator/assets/1220581/07e264b2-ff00-4872-9b91-8001768e1c65">

**Comment by ashleybaldock** [comment]
I think it might actually be something in that in lua, the deck etc. are cleared by assigning an empty table (changing the reference to a new memory container) and in the JS there's clearDeck, which sets the length to 0 but keeps the same reference.

**Comment by ashleybaldock** [comment]
Seems both changes are necessary - I personally prefer the `.every()` fix over the other two.

**Comment by salinecitrine** [comment]
Testing this on the preview deployment, it shows "Iteration limit reached". Initially I thought that this meant it wasn't working, but maybe it's correct? That result would indicate that the wand never reloads (recharges). Do you know if that's also the case in-game? Would be interesting if it let you ignore recharge time on a wand.
